name: Deploy con Docker Compose

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, myke]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Parar servicios anteriores
      run: docker compose -f roxs-voting-app/docker-compose.yml down -v || true

    - name: Construir servicios
      run: docker compose -f roxs-voting-app/docker-compose.yml build

    - name: Levantar servicios
      run: docker compose -f roxs-voting-app/docker-compose.yml up -d

    #- name: Verificar app
    #  run: curl -f http://localhost:3000/