name: Deploy con Docker Compose

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, myke]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

 #   - name: Parar servicios anteriores
 #     run: cd "${GITHUB_WORKSPACE}" && docker compose -f roxs-voting-app/docker-compose.yml down -v || true
    - name: Entrar a directorio de trabajo
      run: cd "/mnt/d/Trabajo/Reto 90 Dias Devops By Roxs/Dia 21/Desafio Final Semana 3/roxs-devops-project90/roxs-voting-app"

    - name: Construir servicios
      run: docker compose -f docker-compose.yml build

    - name: Levantar servicios
      run: docker compose -f docker-compose.yml up -d

    #- name: Verificar app
    #  run: curl -f http://localhost:3000/