name: Deploy con Docker Compose

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, myke]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

 #   - name: Parar servicios anteriores
 #     run: cd "${GITHUB_WORKSPACE}" && docker compose -f roxs-voting-app/docker-compose.yml down -v || true
    - name: Parar servicios anteriores
      working-directory: ./roxs-voting-app
      shell: bash
      run: docker compose -f docker-compose.yml down -v || true

    - name: Construir servicios
      working-directory: ./roxs-voting-app
      run: docker compose -f docker-compose.yml build

    - name: Levantar servicios
      working-directory: ./roxs-voting-app
      run: docker compose -f docker-compose.yml up -d

    #- name: Verificar app
    #  run: curl -f http://localhost:3000/