name: Monitoreo Simple

on:
  schedule:
   # - cron: '*/2 * * * *'  # Cada 2 horas
  workflow_dispatch:

jobs:
  check-app:
    runs-on: [self-hosted, linux, myke]

    steps:
    - name: Chequear estado result
      run: |
        curl -f http://localhost:3000/healthz && echo "\n✅ Result OK" || echo "\n❌ Result caído"

    - name: Chequear estado vote
      run: |
        curl -f http://localhost/healthz && echo "\n✅ Vote OK" || echo "\n❌ Vote caído"
        
